# Site settings
title: Open Sauce
description: > # this means to ignore newlines until "baseurl:"
  An open source recipe collection.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://tetrakai.github.io" # the base hostname & protocol for your site
twitter_username: tetrakazi
github_username: tetrakai
author_url: https://karla.io/

# Build settings
markdown: kramdown
highlighter: pygments
