# Site settings
title: Open Sauce
baseurl: "/open-sauce/"
url: "https://tetrakai.github.io"
twitter_username: tetrakazi
github_username: tetrakai
author_url: https://karla.io/

# Build settings
markdown: kramdown
highlighter: pygments

# Default front matter settings
defaults:
    values:
      layout: recipe